on: [pull_request]
name: test and build
env:
  GOPROXY: "https://proxy.golang.org"
jobs:
  test_amd64:
    strategy:
      matrix:
        go: [1.14, 1.15]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v

  test_arm:
    strategy:
      matrix:
        go: [1.14, 1.15]
    runs-on: [self-hosted, linux, ARM64]
    steps:

      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: go test -v